/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#3895bb",
        "tertiary-container": "#002837",
        "primary-container": "#0a2540",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#49607e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004d66",
        "surface-container-low": "#f2f4f6",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb",
        "primary": "#000f22",
        "on-surface-variant": "#43474d",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#98cbff",
        "on-primary-container": "#768dad",
        "background": "#f7f9fb",
        "on-primary-fixed": "#001c37",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#001d33",
        "on-tertiary-fixed": "#001e2b",
        "secondary": "#00629d",
        "secondary-fixed": "#cfe5ff",
        "tertiary-fixed": "#c0e8ff",
        "on-secondary-container": "#003558",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#00a2fd",
        "surface-dim": "#d8dadc",
        "outline": "#74777e",
        "inverse-primary": "#b0c8eb",
        "primary-fixed": "#d2e4ff",
        "inverse-surface": "#2d3133",
        "outline-variant": "#c4c6ce",
        "primary-fixed-dim": "#b0c8eb",
        "tertiary-fixed-dim": "#7bd1fa",
        "on-secondary-fixed-variant": "#004a77",
        "tertiary": "#00111a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#314865"
      },
      fontFamily: {
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "h2": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "h3": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
